package com.websitethoitrang.entities;
// Generated Dec 6, 2022, 2:28:47 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Taikhoan generated by hbm2java
 */
@Entity
@Table(name = "taikhoan", catalog = "thoitrang")
public class Taikhoan implements java.io.Serializable {

	private String tentk;
	private Khachhang khachhang;
	private String matkhau;
	private String manv;

	public Taikhoan() {
	}

	public Taikhoan(String tentk, String matkhau) {
		this.tentk = tentk;
		this.matkhau = matkhau;
	}

	public Taikhoan(String tentk, Khachhang khachhang, String matkhau, String manv) {
		this.tentk = tentk;
		this.khachhang = khachhang;
		this.matkhau = matkhau;
		this.manv = manv;
	}

	@Id

	@Column(name = "TENTK", unique = true, nullable = false, length = 50)
	public String getTentk() {
		return this.tentk;
	}

	public void setTentk(String tentk) {
		this.tentk = tentk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAKH")
	public Khachhang getKhachhang() {
		return this.khachhang;
	}

	public void setKhachhang(Khachhang khachhang) {
		this.khachhang = khachhang;
	}

	@Column(name = "MATKHAU", nullable = false, length = 16)
	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	@Column(name = "MANV", length = 10)
	public String getManv() {
		return this.manv;
	}

	public void setManv(String manv) {
		this.manv = manv;
	}

}
